spring.application.name=banking-app

spring.datasource.url= jdbc:mysql://localhost:3306/banking_app
spring.datasource.username=root
spring.datasource.password=password
# tells hibernate to automatically create tables using jpa entities
spring.jpa.hibernate.ddl-auto=update

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000